// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqfvkjaqemxemtfcknxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xZnZramFxZW14ZW10ZmNrbnh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1Njg0OTYsImV4cCI6MjA2NDE0NDQ5Nn0.eEW0FaNyUZhpNfR-C7ScsCshI0Gkhf1nmXJGicguSuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);